jsf:
  PROJECT_STAGE: Production
  primefaces:
    theme: bluesky
joinfaces:
  version: @project.parent.version@
spring-boot:
  version: @project.parent.parent.version@
tomcat:
  version: @tomcat.version@
cdi:
  version: @cdi.version@
mojarra:
  version: @javax.faces.version@
omnifaces:
  version: @omnifaces.version@
primefaces:
  version: @primefaces.version@
primefaces-extensions:
  version: @primefaces-extensions.version@
bootsfaces:
  version: @bootsfaces.version@
server:
  port: 8080